services:
  procurement-agent:
    build: ./procurement-agent
    ports:
      - "8003:8000"
    restart: unless-stopped

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "3000:3000"

  # risk-agent:
  #   build: ./risk-agent
  #   ports:
  #     - "8001:8000"

  # scenario-engine:
  #   build: ./scenario-engine
  #   ports:
  #     - "8002:8000"

  # spr-agent:
  #   build: ./spr-agent
  #   ports:
  #     - "8004:8000"

  # coordinator:
  #   build: ./coordinator
  #   ports:
  #     - "8005:8000"
